steps:
  - name: node:14
    entrypoint: npm
    args: ["install"]
    dir: "mesapage"
    id: "instalando-front"
    waitFor: ["-"]
  - name: node:14
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "VUE_APP_BACK_URL=${_VUE_APP_BACK_URL}"
    dir: "mesapage"
    id: "env-front"
    waitFor: ["instalando-front"]
  - name: node:14
    entrypoint: npm
    args: ["run", "build"]
    dir: "mesapage"
    id: "construyendo-front"
    waitFor: ["instalando-front", "env-front"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "mesapage"
    id: "deploy-frontend"
    waitFor: ["env-front", "instalando-front", "construyendo-front"]
  - name: node:14
    entrypoint: npm
    args: ["install"]
    dir: "messa/src"
    id: "instalando-back"
    waitFor: ["-"]
  - name: node:14
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "MONGO_URL=${_MONGO_URL}"
    dir: "messa/src"
    id: "env-back"
    waitFor: ["instalando-back"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "messa/src"
    waitFor: ["env-back", "instalando-back"]
  